/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as FavoriteRouteImport } from './routes/favorite'
import { Route as HelloRouteImport } from './routes/hello'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardPokemonsRouteImport } from './routes/dashboard/pokemons'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as PokemonsPokemonIdRouteImport } from './routes/pokemons/$pokemonId'
import { Route as PokemonsNewRouteImport } from './routes/pokemons/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoriteRoute = FavoriteRouteImport.update({
  id: '/favorite',
  path: '/favorite',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloRoute = HelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPokemonsRoute = DashboardPokemonsRouteImport.update({
  id: '/pokemons',
  path: '/pokemons',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PokemonsPokemonIdRoute = PokemonsPokemonIdRouteImport.update({
  id: '/pokemons/$pokemonId',
  path: '/pokemons/$pokemonId',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonsNewRoute = PokemonsNewRouteImport.update({
  id: '/pokemons/new',
  path: '/pokemons/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/favorite': typeof FavoriteRoute
  '/hello': typeof HelloRoute
  '/dashboard/pokemons': typeof DashboardPokemonsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/pokemons/$pokemonId': typeof PokemonsPokemonIdRoute
  '/pokemons/new': typeof PokemonsNewRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorite': typeof FavoriteRoute
  '/hello': typeof HelloRoute
  '/dashboard/pokemons': typeof DashboardPokemonsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/pokemons/$pokemonId': typeof PokemonsPokemonIdRoute
  '/pokemons/new': typeof PokemonsNewRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/favorite': typeof FavoriteRoute
  '/hello': typeof HelloRoute
  '/dashboard/pokemons': typeof DashboardPokemonsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/pokemons/$pokemonId': typeof PokemonsPokemonIdRoute
  '/pokemons/new': typeof PokemonsNewRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/favorite'
    | '/hello'
    | '/dashboard/pokemons'
    | '/dashboard/settings'
    | '/pokemons/$pokemonId'
    | '/pokemons/new'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorite'
    | '/hello'
    | '/dashboard/pokemons'
    | '/dashboard/settings'
    | '/pokemons/$pokemonId'
    | '/pokemons/new'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/favorite'
    | '/hello'
    | '/dashboard/pokemons'
    | '/dashboard/settings'
    | '/pokemons/$pokemonId'
    | '/pokemons/new'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  FavoriteRoute: typeof FavoriteRoute
  HelloRoute: typeof HelloRoute
  PokemonsPokemonIdRoute: typeof PokemonsPokemonIdRoute
  PokemonsNewRoute: typeof PokemonsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite': {
      id: '/favorite'
      path: '/favorite'
      fullPath: '/favorite'
      preLoaderRoute: typeof FavoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/pokemons': {
      id: '/dashboard/pokemons'
      path: '/pokemons'
      fullPath: '/dashboard/pokemons'
      preLoaderRoute: typeof DashboardPokemonsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/pokemons/$pokemonId': {
      id: '/pokemons/$pokemonId'
      path: '/pokemons/$pokemonId'
      fullPath: '/pokemons/$pokemonId'
      preLoaderRoute: typeof PokemonsPokemonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemons/new': {
      id: '/pokemons/new'
      path: '/pokemons/new'
      fullPath: '/pokemons/new'
      preLoaderRoute: typeof PokemonsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardPokemonsRoute: typeof DashboardPokemonsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardPokemonsRoute: DashboardPokemonsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  FavoriteRoute: FavoriteRoute,
  HelloRoute: HelloRoute,
  PokemonsPokemonIdRoute: PokemonsPokemonIdRoute,
  PokemonsNewRoute: PokemonsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
